lib/generators/policy_machine/templates/migration.rb
lib/policy_machine_storage_adapters/active_record.rb
lib/policy_machine_storage_adapters/active_record/mysql2.rb
lib/policy_machine_storage_adapters/active_record/postgresql.rb
policy_machine.gemspec
spec/policy_machine_storage_adapters/active_record_spec.rb

The recursive branch with no cycles option.  @yzhangmedidata or @mszenher please review and merge.

[MCC-161836] Feature/with recursive nocycle

---

lib/policy_machine_storage_adapters/active_record.rb

^^^ that.
@HonoreDB I could have sworn you once told me stable branches should be just major minor.  Do you think we are ready for ```stable-0.1``` ?

Develop into Master in preparation for stable branch creation

---

policy_machine.gemspec
spec/spec_helper.rb

@HonoreDB it's time
```
Finished in 26.35 seconds
593 examples, 0 failures
Randomized with seed 8512
```

swap out debugger for pry to make multiple ruby version use easy

---

lib/policy_machine/policy_element.rb
lib/policy_machine_storage_adapters/in_memory.rb
spec/policy_machine/association_spec.rb
spec/policy_machine_storage_adapters/in_memory_spec.rb
spec/policy_machine_storage_adapters/neography_spec.rb
spec/policy_machine_storage_adapters/template_spec.rb

@mdsol/team-04 please review and merge.
rspec
```
Finished in 30.97 seconds
677 examples, 0 failures, 12 pending
```

Remove whitespace

---

CONTRIBUTING.md

@HonoreDB please review & merge.

Update the contributing

---

spec/policy_machine_storage_adapters/active_record_spec.rb

This PR updates an error message to give more explicit instructions.

Implement a todo around error reporting

---

lib/policy_machine.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/support/shared_examples_policy_machine.rb

This PR adds the ability to search policy_elements in batches with the postgres adapter

[MCC-233516] - add find_in_batches-like functiniality

---

lib/policy_machine.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine/policy_element_spec.rb
spec/policy_machine_storage_adapters/active_record_spec.rb
spec/support/shared_examples_policy_machine.rb
test/migration.rb

this pr rebases serializers back into develop along with the new batch_find method. grant cucumber tests fail without it.

rebases feature/serializers branch

---

lib/policy_machine_storage_adapters/active_record.rb

Had this locally, PR for the heck of it.

Copypasta was bugging me

---

lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb
spec/support/shared_examples_policy_machine.rb

Develop into Master in preparation for tagging

---

lib/policy_machine_storage_adapters/active_record.rb

Slight improvement (90 ms) on the test case. Specs pass.

Exists generates better sql than any

---

lib/policy_machine/version.rb

@DMcKinnon-mdsol taking it to upcoming version for other pr.
specs:
```
Finished in 32.84 seconds
765 examples, 0 failures, 12 pending
```

bump version number

---

lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

Adds parents to the policy machine active record adapter, and some specs we seemed a little light on.
regression results 
```
Finished in 45 seconds
769 examples, 0 failures, 12 pending
```

[MCC-227826] Feature/parents

---

lib/policy_machine/version.rb

title says it all.  @DMcKinnon-mdsol

bump version in preperation for tagging

---

lib/policy_machine.rb
lib/policy_machine/policy_element.rb
lib/policy_machine/version.rb
spec/support/shared_examples_policy_machine.rb

This PR merges the latest develop into master.

Merge develop into master

---

.travis.yml

This PR configures a Travis build for the policy machine gem. Seems to be past time.

Configure the policy machine to use Travis

---

CHANGELOG.md
lib/policy_machine/version.rb

in preparation for tagging.  @DMcKinnon-mdsol

update version and changelog

---

CHANGELOG.md
lib/policy_machine/policy_element.rb
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb

This PR updates Prohibitions to accept extra attributes. It is used https://github.com/mdsol/dalton/pull/1793.

[MCC-286590] Update Prohibitions to accept extra attributes

---

CHANGELOG.md
lib/policy_machine/version.rb
policy_machine.gemspec

Updating PM version to 1.4.1 in preparation for retagging and consumption with Dalton (https://github.com/mdsol/dalton/pull/1820).

Updated version to 1.4.1

---

lib/policy_machine/version.rb

Update version.rb to 1.5.3

---

README.md

Hi, I'm updating the README accordingly to the up-to-date PolicyMachine's `initialize` method.
There are other issues I've found in the README, but it seemed not trivial to fix as an outsider. I'll document them better in an Issue.

Update README for new PolicyMachine instantiation

---

CHANGELOG.md
lib/migrations/add_initial_policy_machine_tables.rb
lib/migrations/add_logical_links_table.rb
lib/migrations/update_policy_element_associations_table.rb
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
policy_machine.gemspec
test/add_test_columns_migration.rb

This PR upgrades the Policy Machine to Rails 5.2.

[MCC-229209] Upgrade the PM to support Rails 5.2

---

CHANGELOG.md
lib/policy_machine.rb

Reverts mdsol/the_policy_machine#176

Revert "[MCC-634582] Check prohibitions before checking if a priv exists"

---

CHANGELOG.md
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

[MCC-631454] Directly Accessible Objects
