lib/policy_machine_storage_adapters/active_record.rb
lib/policy_machine_storage_adapters/in_memory.rb
spec/support/shared_examples_shared_examples_policy_machine_storage_adapter.rb

One more performance optimization: we're currently generating SQL that does case insensitive comparisons inappropriately, including on the `policy_machine_uuid` column (which should never happen) and on user-created uuid attribute columns (which should be under the user's control), preventing the use of indexes.
This PR modifies the in-memory and active_record backends so you can do `find_all_of_type_object(name: 'Eric', color: 'red', ignore_case: [:name])`. Case insensitivity was never implemented for neo4j.

Allow ignore_case to specify which attributes to ignore case on

---

lib/policy_machine_storage_adapters/active_record.rb

Replaces the ```rescue ::ActiveRecord::RecordNotUnique``` with a ```first_or_create``` to avoid errors related to a failed assignment creation inside a transaction causing subsequent queries to fail. Also, this PR is to develop.  Also, we have a develop now. Also, it's the new default branch. Also, the dalton branch consuming this change is passing ci as well.  @HonoreDB @yzhangmedidata @mszenher.  
specs pass using database_postgres.yml
```
Finished in 21.19 seconds
593 examples, 0 failures
Randomized with seed 14962
```

[MCC-163854] replace rescue with first_or_create

---

spec/support/shared_examples_policy_machine.rb

Blithely assured Yi that we had enough spec coverage for this, then decided he was right and I was wrong.
This spec passes, and should pass given we rely on this behavior, but it's not totally intuitive so I think it's worth having both as documentation and as a more thorough test for `operations=` that involves both adding and removing.
All specs pass for mysql, postgres, and in memory.

Document behavior when overwriting an existing association

---

lib/policy_machine_storage_adapters/active_record.rb

The purpose of this PR is to fix a bug cause by this line. Without this change, if there is any attribute stored in "extra_attributes" that shares the name of an attribute on another model in the application that inherits directly from ActiveRecord::Base, that model will expect that attribute to be stored in "extra_attributes" as well because of this. Targeting the method at PolicyElement fixes this.
@mdsol/team04 @csavage-mdsol @DMcKinnon-mdsol

fixes maudit-client bug by defining methods only on PE and not base

---

lib/policy_machine_storage_adapters/neography.rb

Irritation-driven development--I want to run `rspec` and have it actually pass on all adapters, even the silly ones. This does that.
```
Finished in 1 minute 22.06 seconds
815 examples, 0 failures, 4 pending
Warning: coverage data provided by Coverage [244] exceeds number of lines in /Users/aweiner/the_policy_machine/lib/policy_machine_storage_adapters/neography.rb [243]
Coverage report generated for RSpec to /Users/aweiner/the_policy_machine/coverage. 710 / 714 LOC (99.44%) covered.
```

Add missing features to neography adapter

---

lib/policy_machine_storage_adapters/active_record.rb

Hash keys may be strings (as in a HashWithIndifferentAccess, where .keys always returns a string form even if they started out as symbols). Tolerate that.

Tolerate string keys

---

lib/policy_machine.rb
lib/policy_machine_storage_adapters/active_record.rb
lib/policy_machine_storage_adapters/active_record/postgresql.rb
lib/policy_machine_storage_adapters/template.rb
spec/support/shared_examples_policy_machine.rb

Adds PolicyMachine#accessible_objects method, using the same "slow default implementation, fast(ish) implementation in the activerecord adapter"). 
The mysql adapter seems to have been broken by the Rails update, so I wasn't able to add it to this. It should be a simple change, though. I'll fix mysql in a separate PR.
I haven't performance tested this yet, but if I end up optimizing it further I don't think it'll change the API, which is just `policy_machine.accessible_objects(user_or_user_attribute, operation, [includes: substring], [ignore_prohibitions: true])` returning an array of internal representations of objects.
Specs:
Finished in 2 minutes 18.76 seconds
931 examples, 0 failures, 22 pending
Coverage report generated for RSpec to /Users/aweiner/the_policy_machine/coverage. 776 / …

Add accessible objects list per user and operation

---

lib/policy_machine.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/support/shared_examples_policy_machine.rb

This PR allows PM users to pass in the column name that is to be searched for the purpose of deriving bulk permissions.

allow passing in column name to seach by as key

---

lib/policy_machine_storage_adapters/active_record/postgresql.rb

Not quite ready to call this done, there's lots more savings to get by removing the unnecessary join of Assignment onto the result, and also I don't understand how or why any of this works, but it reduces a 30-second call to a second and a half on sandbox so I'm getting it out there for posterity. The SQL this generates is 
```sql
SELECT "policy_elements".* FROM "policy_elements" WHERE "policy_elements"."id" IN (SELECT assignments__recursive.parent_id FROM "assignments" INNER JOIN (WITH RECURSIVE "assignments__recursive" AS ( SELECT "assignments"."id", "assignments"."parent_id", "assignments"."child_id" FROM "assignments" WHERE "assignments"."child_id" IN (1876421, 1876537, 1879376, 1878545, 1876592, 1876647, 1878453, 1878913, 1879042, 1879211, 1879432, 1879318, 1879317, 1876423, 1879096, …
```

Break recursive queries into multiple calls to avoid confusing the optimizer

---

lib/policy_machine/policy_element.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/support/shared_examples_policy_machine.rb

This PR moves some duplicated logic into the Policy Element base class.
[This spec](https://github.com/mdsol/the_policy_machine/blob/develop/spec/support/shared_examples_policy_machine.rb#L224) is failing. @HonoreDB how much do you like that spec?
rspec
```
Failures:
1) PolicyMachine behaves like a policy machine All methods for policy elements raises when calling policy_classes
Failure/Error: expect{ policy_machine.send(pe_type.to_s.pluralize) }.
expected NoMethodError but nothing was raised
Shared Example Group: "a policy machine" called from ./spec/policy_machine_spec.rb:4
2) ActiveRecord PolicyMachine integration with PolicyMachineStorageAdapter::ActiveRecord behaves like a policy machine All methods for policy elements raises when calling policy_classes
Failure/Error: expect{ …
```

Dry up some code

---

lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

Specs pass. The bulk cleanup of orphaned assignments got wonky and was referencing the unique_identifier, not the id, of deleted elements. If the unique_identifier happened to be a string starting with a number, this would be cast to that number and would delete random assignments.

Join on id, not on implicit cast of unique_identifier string

---

lib/policy_machine_storage_adapters/active_record.rb

Specs pass, seems like it shaves about a second off of the long tail we're trying to fix.

Admit that we're preloading objects into memory and just fetch their ids instead

---

lib/policy_machine_storage_adapters/active_record.rb

As promised, a fix using psychic powers since we can't repro this locally. What I think was going down: we hit method_missing when trying to set a new attribute having never previously referenced it, and the affected code erroneously treats "foo=" as the attribute name. Then, another code path hits `store_attributes` again, and that key becomes a methodized attribute name. Then we try to set `foo=` again, and this time it's defined as an arity-0 getter instead of an arity 1 setter.
Specs pass.

Remove = from the attribute key

---

lib/policy_machine.rb
lib/policy_machine/policy_element.rb
spec/support/shared_examples_policy_machine.rb

The regular finds go through the PolicyElement classes, which wrap the results of the underlying storage engine. The batch finds bypass this to go right to the storage adapter. This usually doesn't have much effect due to duck typing, but means we miss some methods only provided in the wrapper. This PR puts the wrapper back.

Fix abstraction layer skip in batch find

---

lib/policy_machine/warn_once.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

While we're here. I'm not taking out the warning entirely, because it's legitimate (old man shakes fist at clouds), but no reason to fill up sumo and rspec logs with it.

Don't spam the same warning repeatedly within a single process

---

lib/policy_machine_storage_adapters/active_record.rb

This PR prevents us from making a bunch or short but unnecessary calls to the db on buffered stuff.

Remove some db calls

---

lib/policy_machine.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/support/shared_examples_policy_machine.rb

This PR standardizes the response of `batch_pluck`; it now returns an array of symbolic hashes. This is cheaper than creating a struct for each returned element, and matches the format of the input (an array of symbols, representing fields-to-pluck).
Virtual attributes are still not supported for the AR adapter.
@mdsol/team04 please review.

[MCC-288395] Standardize batch_pluck response

---

CHANGELOG.md
CONTRIBUTING.md
lib/policy_machine/policy_element.rb
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb

@jlo188 Noticed that we're receiving quite a few `PG::UniqueViolation` errors in all environments. I traced this back to [AR's find_or_create method not being atomic](http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-find_or_create_by). 

[MCC-291327] Retry find_or_create on index uniqueness violations

---

lib/generators/the_policy_machine/update_policy_element_associations_table_generator.rb
lib/migrations/update_policy_element_associations_table.rb
lib/policy_machine.rb
lib/policy_machine/association.rb
lib/policy_machine/policy_element.rb
lib/policy_machine_storage_adapters/active_record.rb
lib/policy_machine_storage_adapters/in_memory.rb
lib/policy_machine_storage_adapters/neography.rb
lib/policy_machine_storage_adapters/template.rb
spec/policy_machine/association_spec.rb
spec/policy_machine_storage_adapters/active_record_spec.rb
spec/support/shared_examples_policy_machine.rb
spec/support/shared_examples_shared_examples_policy_machine_storage_adapter.rb
test/tasks/setup.rake

Adds an operation set object to an association as the first part of a migration towards single operation sets being associated with a policy element association, eliminating the need for updates to the operation policy element association table

[MCC-276230] Feature/operation set

---

CHANGELOG.md
lib/migrations/update_policy_element_associations_table.rb
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb

So #92 added some import code, but the problem with AR import on duplicate key ignore is that it doesn't update the id of the passed record, so subsequent `operations=` method would fail to create an operation policy element association record.  Also added the partial uniqueness constraint for the policy element association iff it has a operation_set_id here.

[MCC-276230] Fix/new import code

---

CHANGELOG.md
lib/policy_machine/policy_element.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb
spec/support/shared_examples_policy_machine.rb

This PR adds optional attribute filtering to the ActiveRecord `descendants` and `ancestors` methods. This functions similarly to the `query` optional argument in the find methods, and helps limit memory overhead when a smaller subset of results is needed.
Also updates the `method_missing` in the core PolicyElement class to pass arguments through, rather than stripping them.
Finished in 1 minute 38.03 seconds (files took 0.90146 seconds to load)
1553 examples, 0 failures, 19 pending

Added optional filtering to descendants and ancestors methods

---

CHANGELOG.md
lib/policy_machine_storage_adapters/active_record.rb
policy_machine.gemspec
spec/policy_machine_storage_adapters/active_record_spec.rb

In addition to the filters added to the `descendants` and `ancestors` methods, the `parents` and `children` attributes also need that functionality. 
Methodology is the same, adding `where` clauses to the ActiveRecord relations via chaining. Tests and version updated to match.

Add optional filters to parents and children attribute accessors

---

CHANGELOG.md
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
policy_machine.gemspec
spec/policy_machine_storage_adapters/active_record_spec.rb
spec/support/shared_examples_policy_machine.rb

`store_attributes` previously would overwrite accessors for actual columns with extra_attributes accessors when there was a conflict. This PR gives precedence to the column accessors, only defining accessors for non-existent attributes.

[MCC-305829] Give precedence to column accessors over extra_attributes

---

lib/policy_machine/version.rb
policy_machine.gemspec

pretty much says it all on the tin.  Switched the unloaded module declaration to a class declaration since it conflicts with the class load later

[MCC-???] use existing version file instead of string in gemspec

---

CHANGELOG.md
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
lib/policy_machine_storage_adapters/active_record/postgresql.rb
spec/support/shared_examples_policy_machine.rb

This PR fixes a bug in the active record storage adapter's `accessible_objects` method. Previously this method was not returning the correct operation set ids because our sql was a little off.
Thanks @CGDS for the fix.
@mdsol/team04 please review.

[MCC-321135] Fix bug in accessible objects

---

spec/policy_machine_storage_adapters/active_record_spec.rb

This PR reshuffles and more clearly defines the relationships between test elements, because the previous block of code was nigh unreadable. I tried to be more rigid with object definitions and attributes... e.g. all users are now 'blue', user attributes are 'green', etc.
Should make it easier to introduce graph traversals into the PM down the road. (read: soon)

Reorganize graph connection AR specs for clarity

---

CHANGELOG.md
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

This PR contains the trivial implementation of plucking attributes from PolicyElement relatives. It literally chains `pluck` onto the end of the other methods, then zips the result with the attribute names, leading to a result of the form...
```
[{ name: 'bob', profession: 'spartan' }, { name: 'wirt', profession: 'frog' }
```
Please review.

[MCC-317560] Graph pluck via method chaining

---

CHANGELOG.md
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
lib/policy_machine_storage_adapters/active_record/postgresql.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

The goal is to, from a root node, pluck all the attributes from ancestors of ancestors. This is to bypass the memory overhead of instantiating ancestor objects to determine inherited attributes, and remove the n+1 problem inherent in `pluck`ing from each ancestor in turn.
This will be PM version 1.7.0.

[MCC-343261] Pluck ancestor tree with attributes

---

CHANGELOG.md
lib/policy_machine/version.rb
policy_machine.gemspec

v1.7.1 of the Policy Machine added a '~> 0.15.0' version restriction to the 'pg' gem (dependency only when using an ActiveRecord storage adapter). Since 1.0.0 was the first 'pg' version which invalidated the Rails integration, this PR loosens the version requirement to sub-1.0.0.

Loosen 'pg' gem dependency to '< 1.0.0'

---

lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

This PR modifies the `find_all_of_type_#{pe_type}` method definition to allow for passing arrays as arguments to find records matching any of the elements in the array. 
Previously, this worked with only very specific conditions due to the logic that determines the `all` variable. I believe that you could pass arrays when finding based on a column attribute besides `name`. 
Note that this method still is extremely inefficient for querying on the `extra_attributes` column, as all searching is done in-memory. There is still a **lot** of potential performance improvements in this method, and it's used frequently enough that I think work in the future could drastically improve performance across many workflows. 
@mdsol/team04 - please review.

[MCC-404025] Allow array parameters for finding records

---

CHANGELOG.md
lib/policy_machine_storage_adapters/active_record.rb

This PR fixes the public interface of the PM to expose the `class_for_type` method.

[MCC-404025] Make class_for_type public

---

CHANGELOG.md
lib/policy_machine.rb
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

This PR adds a `accessible_ancestor_objects` method to the ActiveRecord storage adapter. This method adds object scoping to the existing `accessible_objects` method. An object is only "accessible" if it is an ancestor of the specified root object.

[MCC-361558] Add accessible_ancestor_objects to ActiveRecord storage adapter

---

CHANGELOG.md
lib/policy_machine.rb
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

This PR updates the Policy Machine to allow filtering privilege APIs so they only return privileges (or whether a privilege exists) if it is derived via a user attribute that passes the filter.

[MCC-224756] Filter privileges by user attribute

---

CHANGELOG.md
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

This PR fixes the JSON serialization of the `extra_attributes` column in the ActiveRecord adapter's PolicyElement class.
Previously, empty `extra_attributes` entries were stored as `null` values. Now, they'll properly be JSON representations of empty hashes. 
@mdsol/team04 - please review

[MCC-229209 Fix JSON serialization of the extra_attributes column

---

CHANGELOG.md
lib/policy_machine.rb
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

This PR moves the method `associations_filtered_by_operation` to public visibility in the ActiveRecord storage adapter. This method allows policy element associations to be filtered to just those containing the specified operation.

[MCC-468035] Move associations_filtered_by_operation to public visibility

---

CHANGELOG.md
lib/policy_machine.rb
lib/policy_machine/version.rb
spec/support/shared_examples_policy_machine.rb

This PR adds an `include_prohibitions` option to the `#scoped_privileges` method in the PolicyMachine. This option returns all prohibitions the user (attribute) has on the specified object (attribute) alongside their derived privileges.

[MCC-468036] Add include_prohibitions filter to #scoped_privileges

---

CHANGELOG.md
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
lib/policy_machine_storage_adapters/active_record/postgresql.rb

Hi, this PR adds optimizations to the ActiveRecord Adapter's `accessible_ancestor_objects` method. It moves a lot of the logic from Ruby to raw SQL. In benchmarks with trivial amounts of data, this new method is approximately 3.5x as fast as the old method: 
```ruby
old = lambda { ado_pm.accessible_ancestor_objects(u1, bluff, grandparent_fish, key: :unique_identifier) }
new = lambda { ado_pm.policy_machine_storage_adapter.new_accessible_ancestor_objects(u1, bluff, grandparent_fish, key: :unique_identifier) }
Benchmark.ips do |x|
x.report("old") { old.call }
x.report("new") { new.call }
x.compare!
end
<<-RESULTS
Warming up --------------------------------------
old     7.000  i/100ms
new    26.000  i/100ms
Calculating -------------------------------------
old     74.303  (± 2.7%) i/s - …
```

[MCC-488586] Optimize accessible ancestor objects

---

spec/policy_machine_storage_adapters/active_record_spec.rb

As the specs for `'scoping privileges by user attribute'` get more complicated, the variable names chosen for the users, user attributes, objects, and object attributes are becoming harder to follow. This PR reverts them to conventional names for readability.
Targets `allow_association_preload`.

[MCC-521095] Genericize Active Record specs

---

CHANGELOG.md
lib/policy_machine.rb
lib/policy_machine/version.rb
lib/policy_machine_storage_adapters/active_record.rb
spec/policy_machine_storage_adapters/active_record_spec.rb

This PR updates `.accessible_ancestor_objects` to support an optional argument `associations_with_operation`. This bypasses the loading of PolicyElementAssociations for the user with the specified operation, if the relation has already been loaded.
Also updates the `options` argument to a keyword argument to reflect the optional `associations_with_operation`.

[MCC-521095] Allow preloading of policy element associations in .accessible_ancestor_objects

---

CHANGELOG.md
lib/policy_machine.rb

Background
- When performing a privilege exists lookup, Dalton (via the policy machine) checks if an operator is prohibited on the requested operable after it has checked if the user has access the to the given operable via the requested permission.
Changes
- Check prohibitions first before performing privilege derivation.
Tests
- Sample size of 1000
- Setting `ignore_prohibitions` to `true` results in an average response time of 1.42751863352 seconds
- Setting `ignore_prohibitions`to `false` results in an average response time of 2.19180535417 seconds 
Setting `ignore_prohibitions` to `true` is ~53.54% faster.

[MCC-634582] Check prohibitions before checking if a priv exists
